version: '3.8'
services:
  db:
    build: ./db
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./data:/data
    ports:
      - '5432:5432'
    networks:
      - db-network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U user -d db
      interval: 8s
      timeout: 5s
      retries: 3
  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4:6.11"
    env_file:
      - ./database.env
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - db-network
networks:
  db-network:
    driver: bridge
